import os
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(BASE_DIR)  # Ir un nivel arriba de modules/
LOGS_DIR = os.path.join(BASE_DIR, "logs")
DATABASES_DIR = os.path.join(BASE_DIR, "databases")

os.makedirs(LOGS_DIR, exist_ok=True)
os.makedirs(DATABASES_DIR, exist_ok=True)

GEOLITE_DB_PATH = os.path.join(DATABASES_DIR, "GeoLite2-Country.mmdb")
THREATFOX_DB_PATH = os.path.join(DATABASES_DIR, "threatfox_ips.txt")
SPAMHAUS_DB_PATH = os.path.join(DATABASES_DIR, "spamhaus_drop.txt")

DNS_LOG_FILE = os.path.join(LOGS_DIR, "dns_queries.json")
CONNECTIONS_LOG_FILE = os.path.join(LOGS_DIR, "connections.json")
TLS_SNI_LOG_FILE = os.path.join(LOGS_DIR, "tls_sni.json")

THREATFOX_URL = "https://threatfox.abuse.ch/downloads/ip_reporter.json"

THREATFOX_ALT_URLS = [
    "https://bazaar.abuse.ch/export/csv/ip/",
    "https://feodotracker.abuse.ch/downloads/ipblocklist.json",
]

FEODO_URL = "https://feodotracker.abuse.ch/downloads/ipblocklist.json"
URLHAUS_URL = "https://urlhaus.abuse.ch/downloads/csv_referrer/"

SPAMHAUS_DROP_URL = "https://www.spamhaus.org/drop/drop.txt"
SPAMHAUS_EDROP_URL = "https://www.spamhaus.org/drop/edrop.txt"

GEOLITE_DOWNLOAD_URL = "https://download.maxmind.com/app/geoip_download"

WHITELIST_DOMAINS = {
    "google.com",
    "googleapis.com",
    "googleusercontent.com",
    "gstatic.com",
    "youtube.com",
    "ytimg.com",
    "googlevideo.com",
    "github.com",
    "githubusercontent.com",
    "githubassets.com",
    "amazonaws.com",
    "aws.amazon.com",
    "cloudfront.net",
    "cloudflare.com",
    "cloudflare.net",
    "microsoft.com",
    "microsoftonline.com",
    "windows.com",
    "windows.net",
    "apple.com",
    "icloud.com",
    "mzstatic.com",
    "facebook.com",
    "fbcdn.net",
    "meta.com",
    "twitter.com",
    "twimg.com",
    "x.com",
    "reddit.com",
    "redd.it",
    "stackexchange.com",
    "stackoverflow.com",
    "docker.com",
    "docker.io",
    "python.org",
    "pypi.org",
    "pip.org",
    "ubuntu.com",
    "canonical.com",
    "debian.org",
    "mozilla.org",
    "firefox.com",
    "wikipedia.org",
    "wikimedia.org",
    "netflix.com",
    "nflxvideo.net",
    "spotify.com",
    "scdn.co",
    "telegram.org",
    "telegram.me",
    "discord.com",
    "discordapp.net",
    "slack.com",
    "slack-edge.com",
    "zoom.us",
    "dropbox.com",
    "dropboxusercontent.com",
    "1password.com",
    "bitwarden.com",
    "nordvpn.com",
    "nordcdn.com",
    "expressvpn.com",
    "duckduckgo.com",
    "bing.com",
    "yahoo.com",
    "baidu.com",
    "akamai.com",
    "fastly.com",
    "heroku.com",
    "render.com",
    "vercel.com",
    "netlify.com",
    "digitalocean.com",
    "linode.com",
    "vultr.com",
    "godaddy.com",
    "namecheap.com",
    "cloudns.io",
    "letsencrypt.org",
    "digicert.com",
    "globalsign.com",
    "paypal.com",
    "visa.com",
    "mastercard.com",
    "amex.com",
    "steamcommunity.com",
    "steampowered.com",
    "epicgames.com",
    "unrealengine.com",
    "roblox.com",
    " twitch.tv",
    "ttvnw.net",
    "openstreetmap.org",
    "cloudinary.com",
    "sendgrid.net",
    "mailgun.org",
    "postmarkapp.com",
    "stripe.com",
    "braintreepayments.com",
    "shopify.com",
    "walmart.com",
    "target.com",
    "bestbuy.com",
    "cnn.com",
    "bbc.com",
    "nytimes.com",
    "theguardian.com",
    "reuters.com",
    "apnews.com",
    "bloomberg.com",
    "imdb.com",
    "rottentomatoes.com",
    "whatsapp.com",
    "whatsapp.net",
    "signal.org",
    "zoom.us",
    "webex.com",
    "atlassian.com",
    "jira.com",
    "confluence.com",
    "salesforce.com",
    "force.com",
    "adobe.com",
    "adobelogin.com",
    "creativecloud.com",
    "docusign.com",
    "zendesk.com",
    "freshdesk.com",
    "hubspot.com",
    "mailchimp.com",
    "buffer.com",
    "hootsuite.com",
    "canva.com",
    "figma.com",
    "notion.so",
    "notioncdn.com",
    "airtable.com",
    "todoist.com",
    "evernote.com",
    "trello.com",
    "asana.com",
    "monday.com",
    "clickup.com",
    "linear.app",
    "slite.com",
    "obsidian.md",
    "notepad-plus-plus.org",
    "sublimetext.com",
    "vim.org",
    "gnu.org",
    "kernel.org",
    "archlinux.org",
    "fedora.org",
    "centos.org",
    "gentoo.org",
    "freebsd.org",
    "openbsd.org",
    "apache.org",
    "nginx.com",
    "mariadb.org",
    "postgresql.org",
    "mysql.com",
    "redis.io",
    "mongodb.com",
    "elastic.co",
    "influxdata.com",
    "grafana.com",
    "prometheus.io",
    "jenkins.io",
    "gitlab.com",
    "bitbucket.org",
    "npmjs.com",
    "yarnpkg.com",
    "nuget.org",
    "crates.io",
    "rubygems.org",
    "packagist.org",
    "maven.apache.org",
    "gradle.org",
    "kubernetes.io",
    "k8s.io",
    "istio.io",
    "helm.sh",
    "terraform.io",
    "packer.io",
    "vagrantup.com",
    "ansible.com",
    "puppet.com",
    "saltstack.com",
    "docker.com",
    "kubernetes.io",
    "quay.io",
    "gcr.io",
    "ghcr.io",
    "mcr.io",
    "readthedocs.org",
    " RTD",
    "w3.org",
    "ietf.org",
    "rfc-editor.org",
    "icann.org",
    "arin.net",
    "ripe.net",
    "apnic.net",
    "lacnic.net",
    "afrinic.net",
    "nist.gov",
    "cisa.gov",
    "speedtest.net",
    "fast.com",
    "shodan.io",
    "censys.io",
    " VirusTotal",
    "virustotal.com",
    "abuse.ch",
    "threatfox.abuse.ch",
    "malwarebazaar.abuse.ch",
    "spamhaus.org",
    "alienvault.com",
    "otx.alienvault.com",
    "threatconnect.com",
    "mnemonic.no",
    "dshield.org",
    " Emerging Threats",
    " EmergingThreats.net",
}

WHITELIST_IP_RANGES = [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "224.0.0.0/4",
    "240.0.0.0/4",
    "0.0.0.0/8",
    "100.64.0.0/10",
    "192.0.0.0/24",
    "192.0.2.0/24",
    "198.51.100.0/24",
    "203.0.113.0/24",
]

RISK_LEVELS = {
    "safe": {"level": "🟢", "score": 0, "description": "Seguro"},
    "whitelisted": {"level": "🟢", "score": 0, "description": "En lista blanca"},
    "unknown": {"level": "🟡", "score": 25, "description": "Desconocido"},
    "suspicious": {"level": "🟠", "score": 50, "description": "Suspicious"},
    "dangerous": {"level": "🔴", "score": 100, "description": "Peligroso"},
}

RISK_THRESHOLDS = {
    "low": 25,
    "medium": 50,
    "high": 75,
}

DNS_QUERY_TYPES = ["A", "AAAA", "MX", "NS", "CNAME", "TXT", "SOA", "PTR", "SRV", "ANY"]

PROTOCOL_NAMES = {
    6: "TCP",
    17: "UDP",
    1: "ICMP",
    47: "GRE",
    50: "ESP",
    51: "AH",
    58: "ICMPv6",
}

COMMON_PORTS = {
    20: "FTP-DATA",
    21: "FTP",
    22: "SSH",
    23: "TELNET",
    25: "SMTP",
    53: "DNS",
    67: "DHCP",
    68: "DHCP",
    80: "HTTP",
    110: "POP3",
    143: "IMAP",
    443: "HTTPS",
    445: "SMB",
    465: "SMTPS",
    587: "SMTP-MSA",
    993: "IMAPS",
    995: "POP3S",
    1433: "MSSQL",
    1521: "ORACLE",
    3306: "MYSQL",
    3389: "RDP",
    5432: "POSTGRESQL",
    5900: "VNC",
    6379: "REDIS",
    8080: "HTTP-PROXY",
    8443: "HTTPS-ALT",
    27017: "MONGODB",
}

SUSPICIOUS_PORTS = {
    4444: "Metasploit",
    5555: "Android ADB",
    6667: "IRC",
    31337: "Backorifice",
    12345: "NetBus",
    27374: "SubSeven",
    3128: "HTTP-PROXY",
    8080: "HTTP-PROXY",
    8888: "HTTP-PROXY",
    1080: "SOCKS",
    9050: "TOR",
    9150: "TOR",
}

ALERT_PORTS = {
    4444: "Metasploit default - posible compromiso",
    5555: "Android Debug Bridge - posible compromiso",
    31337: "Back Orifice - malware conocido",
    12345: "NetBus - troyano",
    27374: "SubSeven - troyano",
    6667: "IRC - posible bot IRC",
}


def get_config():
    return {
        "base_dir": BASE_DIR,
        "logs_dir": LOGS_DIR,
        "databases_dir": DATABASES_DIR,
        "geolite_db_path": GEOLITE_DB_PATH,
        "threatfox_db_path": THREATFOX_DB_PATH,
        "spamhaus_db_path": SPAMHAUS_DB_PATH,
        "dns_log_file": DNS_LOG_FILE,
        "connections_log_file": CONNECTIONS_LOG_FILE,
        "tls_sni_log_file": TLS_SNI_LOG_FILE,
    }
